### ISSUE TITLE
Repositories table / graphql query MockedProvider tests

### ISSUE THREAD

**Issue by mrcodegit** [KanhaKanha123/repositories-listing#3]
Could you please add some tests around the repositories table / graphql query using <MockedProvider>?
https://www.apollographql.com/docs/react/development-testing/testing/#the-mockedprovider-component

**Comment by KanhaKanha123** [comment]
The all important files and custom hooks are covered with tests as you mentioned above. Please let me know you want more files also to cover i will write for those too.
