### ISSUE TITLE
package.json dependencies

### ISSUE THREAD

**Issue by mrcodegit** [KanhaKanha123/repositories-listing#4]
Are all dependencies needed in 'dependencies' array? could we put some of them in a different place?

**Comment by KanhaKanha123** [comment]
I separated dev(unit testing related) and normal decencies for production, please check.

**Comment by mrcodegit** [comment]
how about @types?

**Comment by KanhaKanha123** [comment]
you are right types also should be dev dependancy as we are not creating a custom package that re-export the types. So they should be in dev too. Sorry my bad. do you want me to push to dev and push the code?

**Comment by mrcodegit** [comment]
No need to push, comment is enough, thanks!
